# How many seconds a player has to wait before teleporting again.
teleport-cooldown: 100

# How many homes a player can have.
total-homes: 5

# Use a GUI for /homes.
# Players can click on the homes to teleport, rather than type /home <home>.
use-homes-gui: true

# Allow users to set a home they will respawn at when they die.
allow-respawn-at-home: true

# No touch please :)
config-version: 2