name: EzHomes
version: ${project.version}
main: lol.hyper.ezhomes.EzHomes
api-version: 1.16
author: hyperdefined
description: A simple homes plugin.
commands:
  sethome:
    usage: /sethome <name>
    description: Set home.
  home:
    usage: /home <name>
    description: Teleport to home.
  homes:
    usage: /homes
    description: List player homes.
  updatehome:
    usage: /updatehome
    description: Update a home location.
  delhome:
    usage: /delhome
    description: Delete a home.
  homesreload:
    usage: /homesreload
    description: Reloads config.
  where:
    usage: /where
    description: Shows a home's location.
permission:
  ezhomes.reload:
    default: op
  ezhomes.bypasslimit:
    default: op
  ezhomes.bypasscooldown:
    default: op