name: EzHomes
version: ${project.version}
main: lol.hyper.ezhomes.EzHomes
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/ezhomes.82663/
description: A super easy to use homes plugin.
commands:
  sethome:
    usage: /sethome <name>
    description: Set home.
  home:
    usage: /home <name>
    description: Teleport to home.
  homes:
    usage: /homes
    description: List player homes.
  updatehome:
    usage: /updatehome
    description: Update a home location.
  delhome:
    usage: /delhome
    description: Delete a home.
  where:
    usage: /where
    description: Shows a home's location.
  respawnhome:
    usage: /respawnhome
    description: Set a home to respawn at.
  ezhomes:
    usage: /ezhomes
permissions:
  ezhomes.reload:
    default: op
    description: Allows the usage of /ezhomes reload
  ezhomes.bypasslimit:
    default: op
    description: Allows player to bypass home limit
  ezhomes.bypasscooldown:
    default: op
    description: Allows player to bypass cooldown between teleports
libraries:
  - org.json:json:20211205
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-text-minimessage:4.10.1
  - net.kyori:adventure-platform-bukkit:4.1.0